version: "3"
services:
  frontend-install:
    build: 
      context: ./frontend-install
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend-install/src:/app/src
  frontend-template:
    build: 
      context: ./frontend-template
      dockerfile: Dockerfile
    ports:
      - "3010:3010"
    volumes:
      - ./frontend-template/src:/app/src
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    links:
      - redis
  mongo:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: test
      MONGO_INITDB_ROOT_PASSWORD: testpass
    volumes:
      - ./mongo:/data/db
    ports:
      - "27017:27017"
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
