version: "3"
services:
  frontend-install:
    build: 
      context: ./frontend-install
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend-install/src:/app/src